<a href="https://colab.research.google.com/github/elkinbarretorojas/data_science/blob/main/Exploratory_data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploratory data analysis (EDA) | Fuel Economy Prediction.

## Introduction

**What data are we exploring today ?**

The data-set can be downloaded from [here](https://www.kaggle.com/CooperUnion/cardataset). To give a piece of brief information about the data set this data contains more of 10, 000 rows and more than 10 columns which contains features of the car such as Engine Fuel Type, Engine HP, Transmission Type, highway MPG, city MPG and many more. So in this opportunity, we will perform a Exploratory data analysis, make it ready for modeling, and predict the Fuel Economy (MPG).



---

## 1. Importing the required libraries for EDA

Below are the libraries that are used in order to perform EDA and Random Forect Regressor

In [34]:
import pandas as pd
import numpy as np
import seaborn as sns                       #visualisation
import matplotlib.pyplot as plt             #visualisation
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline
sns.set(color_codes=True)
from scipy.stats import shapiro
from scipy.stats import kstest
from scipy.stats import chisquare
import math
import stats

## 2. Loading the data into the data frame.

In [4]:
df = pd.read_csv("raw_data.csv")
cars_data = df
# To display the top 5 rows
cars_data.head(5)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [5]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB

In [6]:
cars_data.describe()

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
count,11914.000000,11845.00000,11884.000000,11908.000000,11914.000000,11914.000000,11914.000000,1.191400e+04
mean,2010.384338,249.38607,5.628829,3.436093,26.637485,19.733255,1554.911197,4.059474e+04
std,7.579740,109.19187,1.780559,0.881315,8.863001,8.987798,1441.855347,6.010910e+04
min,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
25%,2007.000000,170.00000,4.000000,2.000000,22.000000,16.000000,549.000000,2.100000e+04
50%,2015.000000,227.00000,6.000000,4.000000,26.000000,18.000000,1385.000000,2.999500e+04
75%,2016.000000,300.00000,6.000000,4.000000,30.000000,22.000000,2009.000000,4.223125e+04
max,2017.000000,1001.00000,16.000000,4.000000,354.000000,137.000000,5657.000000,2.065902e+06

Insights:

- Year: The minimum year in dataset is 1990, average year is 2010 and maximum year is 2017.
- Engine Hp:: The minimum hp in dataset is 55, average hp is 249 and maximum hp is 1001.
- Engine Cylinders: The minimum cylinders in dataset are 0, average cylinders are 5 and maximum cylindes are 16.
- Number of doors: The minimum doors a car have are 2, on average, the number of doors are 3 and maximum doors are 4.
- Highway mpg: The minimum highway mpg in dataset is 12, average highway mpg is 26.6 and maximum highway mpg is 354.
- City mpg: The minimum city mpg in dataset is 7, average city mpg is 19.7 and maximum city mpg is 137.
- Popularity: The minimum popularity of a car in dataset is 2, average car popularity is 1554.9 and maximum car popularity is 5657.
- Price: The minimum car price in dataset is 2000, average car price is 40K and maximum car price is 2.06 million.

## 3. Checking the types of data

In [13]:
cars_data.dtypes

make             object
model            object
year              int64
fuel_type        object
hp              float64
cylinders       float64
transmission     object
drive            object
doors           float64
size             object
style            object
highway_mpg       int64
city_mpg          int64
popularity        int64
price             int64
dtype: object

## 4. Renaming columns and dropping columns

In [15]:
cars_data.columns = cars_data.columns.str.lower().str.replace(" ", "_")

In [17]:
print('Number of duplicates are : ', cars_data.duplicated().sum())
cars_data = cars_data.drop_duplicates()

Number of duplicates are :  0

In [18]:
print('Number of missing values in each columns are below : ')
print(cars_data.isnull().sum())

Number of missing values in each columns are below :
make             0
model            0
year             0
fuel_type        3
hp              69
cylinders       30
transmission     0
drive            0
doors            6
size             0
style            0
highway_mpg      0
city_mpg         0
popularity       0
price            0
dtype: int64

From the above, we can conclude that Market column has a lot of null values. Then, we will drop that column.

In [30]:
#cars_data.drop('market', axis = 1, inplace = True)
cars_data

,make,model,year,fuel_type,hp,cylinders,transmission,drive,doors,size,style,highway_mpg,city_mpg,popularity,price
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Midsize,Sedan,26,17,61,28995

## 7. Handling missing or null values.

In [20]:
null_values = cars_data[cars_data.isnull().any(axis = 1)]
null_values

,make,model,year,fuel_type,hp,cylinders,transmission,drive,doors,size,style,highway_mpg,city_mpg,popularity,price
539,FIAT,500e,2015,electric,NaN,0.0,DIRECT_DRIVE,front wheel drive,2.0,Compact,2dr Hatchback,108,122,819,31800
540,FIAT,500e,2016,electric,NaN,0.0,DIRECT_DRIVE,front wheel drive,2.0,Compact,2dr Hatchback,103,121,819,31800
541,FIAT,500e,2017,electric,NaN,0.0,DIRECT_DRIVE,front wheel drive,2.0,Compact,2dr Hatchback,103,121,819,31800
1983,Chevrolet,Bolt EV,2017,electric,200.0,NaN,DIRECT_DRIVE,front wheel drive,4.0,Compact,4dr Hatchback,110,128,1385,40905
1984,Chevrolet,Bolt EV,2017,electric,200.0,NaN,DIRECT_DRIVE,front wheel drive,4.0,Compact,4dr Hatchback,110,128,1385,36620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9853,Kia,Soul EV,2016,electric,NaN,0.0,DIRECT_DRIVE,front wheel drive,4.0,Compact,Wagon,92,120,1720,31950
9854,Kia,Soul EV,2016,electric,NaN,0.0,DIRECT_DRIVE,front wheel drive,4.0,Compact,Wagon,92,120,1720,35950
11321,Suzuki,Verona,2004,NaN,155.0,6.0,AUTOMATIC,front wheel drive,4.0,Midsize,Sedan,25,17,481,17199
11322,Suzuki,Verona,2004,NaN,155.0,6.0,AUTOMATIC,front wheel drive,4.0,Midsize,Sedan,25,17,481,20199
11323,Suzuki,Verona,2004,NaN,155.0,6.0,AUTOMATIC,front wheel drive,4.0,Midsize,Sedan,25,17,481,18499

Hp has null values. Hp will be filled by 0 as the cars having null values are electric cars. So they don't have Hp in general

In [21]:
cars_data['hp'] = cars_data['hp'].fillna(0)

Fuel type null values will be fill with the mode found it before "regular unleaded" as this columns is a categorical one.

In [22]:
cars_data['fuel_type'].mode()
cars_data['fuel_type'] = cars_data['fuel_type'].fillna('regular unleaded')

We know that electric cars doesn't have any cylinders so the null values will be again filled with 0

In [23]:
cars_data['fuel_type'] = cars_data['fuel_type'].fillna(0)

 Doors will be fill with Mean (Integer) as it is a numerical value. And we can not have decimal numbers here.

In [24]:
cars_data['doors'] = cars_data['doors'].fillna(cars_data['doors'].mean())
null_check = cars_data[cars_data.isnull().any(axis=1)]
null_check

,make,model,year,fuel_type,hp,cylinders,transmission,drive,doors,size,style,highway_mpg,city_mpg,popularity,price
1983,Chevrolet,Bolt EV,2017,electric,200.0,NaN,DIRECT_DRIVE,front wheel drive,4.0,Compact,4dr Hatchback,110,128,1385,40905
1984,Chevrolet,Bolt EV,2017,electric,200.0,NaN,DIRECT_DRIVE,front wheel drive,4.0,Compact,4dr Hatchback,110,128,1385,36620
3716,Volkswagen,e-Golf,2015,electric,115.0,NaN,DIRECT_DRIVE,front wheel drive,4.0,Compact,4dr Hatchback,105,126,873,33450
3717,Volkswagen,e-Golf,2015,electric,115.0,NaN,DIRECT_DRIVE,front wheel drive,4.0,Compact,4dr Hatchback,105,126,873,35445
3718,Volkswagen,e-Golf,2016,electric,115.0,NaN,DIRECT_DRIVE,front wheel drive,4.0,Compact,4dr Hatchback,105,126,873,28995
3719,Volkswagen,e-Golf,2016,electric,115.0,NaN,DIRECT_DRIVE,front wheel drive,4.0,Compact,4dr Hatchback,105,126,873,35595
5778,Mitsubishi,i-MiEV,2014,electric,0.0,NaN,DIRECT_DRIVE,rear wheel drive,4.0,Compact,4dr Hatchback,99,126,436,22995
5779,Mitsubishi,i-MiEV,2016,electric,66.0,NaN,DIRECT_DRIVE,rear wheel drive,4.0,Compact,4dr Hatchback,99,126,436,22995
5780,Mitsubishi,i-MiEV,2017,electric,66.0,NaN,DIRECT_DRIVE,rear wheel drive,4.0,Compact,4dr Hatchback,102,121,436,22995
8373,Toyota,RAV4 EV,2012,electric,154.0,NaN,DIRECT_DRIVE,front wheel drive,4.0,Midsize,4dr SUV,74,78,2031,49800
8695,Mazda,RX-7,1993,regular unleaded,255.0,NaN,MANUAL,rear wheel drive,2.0,Compact,Coupe,23,15,586,7523
8696,Mazda,RX-7,1994,regular unleaded,255.0,NaN,MANUAL,rear wheel drive,2.0,Compact,Coupe,23,15,586,8147
8697,Mazda,RX-7,1995,regular unleaded,255.0,NaN,MANUAL,rear wheel drive,2.0,Compact,Coupe,23,15,586,8839
8698,Mazda,RX-8,2009,premium unleaded (required),232.0,NaN,MANUAL,rear wheel drive,4.0,Compact,Coupe,22,16,586,31930
8699,Mazda,RX-8,2009,premium unleaded (required),212.0,NaN,AUTOMATIC,rear wheel drive,4.0,Compact,Coupe,23,16,586,26435
8700,Mazda,RX-8,2009,premium unleaded (required),232.0,NaN,MANUAL,rear wheel drive,4.0,Compact,Coupe,22,16,586,27860
8701,Mazda,RX-8,2009,premium unleaded (required),232.0,NaN,MANUAL,rear wheel drive,4.0,Compact,Coupe,22,16,586,31000
8702,Mazda,RX-8,2009,premium unleaded (required),232.0,NaN,MANUAL,rear wheel drive,4.0,Compact,Coupe,22,16,586,26435
8703,Mazda,RX-8,2009,premium unleaded (required),212.0,NaN,AUTOMATIC,rear wheel drive,4.0,Compact,Coupe,23,16,586,31700
8704,Mazda,RX-8,2009,premium unleaded (required),212.0,NaN,AUTOMATIC,rear wheel drive,4.0,Compact,Coupe,23,16,586,28560
8705,Mazda,RX-8,2010,premium unleaded (required),232.0,NaN,MANUAL,rear wheel drive,4.0,Compact,Coupe,22,16,586,32140
8706,Mazda,RX-8,2010,premium unleaded (required),212.0,NaN,AUTOMATIC,rear wheel drive,4.0,Compact,Coupe,23,16,586,26645
8707,Mazda,RX-8,2010,premium unleaded (required),212.0,NaN,AUTOMATIC,rear wheel drive,4.0,Compact,Coupe,23,16,586,32810
8708,Mazda,RX-8,2010,premium unleaded (required),232.0,NaN,MANUAL,rear wheel drive,4.0,Compact,Coupe,22,16,586,26645
8709,Mazda,RX-8,2010,premium unleaded (required),232.0,NaN,MANUAL,rear wheel drive,4.0,Compact,Coupe,22,16,586,32110
8710,Mazda,RX-8,2011,premium unleaded (required),212.0,NaN,AUTOMATIC,rear wheel drive,4.0,Compact,Coupe,23,16,586,32960
8711,Mazda,RX-8,2011,premium unleaded (required),232.0,NaN,MANUAL,rear wheel drive,4.0,Compact,Coupe,22,16,586,32260
8712,Mazda,RX-8,2011,premium unleaded (required),232.0,NaN,MANUAL,rear wheel drive,4.0,Compact,Coupe,22,16,586,32290
8713,Mazda,RX-8,2011,premium unleaded (required),232.0,NaN,MANUAL,rear wheel drive,4.0,Compact,Coupe,22,16,586,26795
8714,Mazda,RX-8,2011,premium unleaded (required),212.0,NaN,AUTOMATIC,rear wheel drive,4.0,Compact,Coupe,23,16,586,26795

## 8. Separating the numerical and categorical columns

In [25]:
num_col = cars_data.select_dtypes(include = [np.number])
cat_col = cars_data.select_dtypes(exclude = [np.number])

## 8. Detecting Outlierss

In [36]:
#for i in num_col:
#    fig = px.box(cars_data)
#    #fig.update_traces(fillcolor = '#C9A26B')
#    fig.show()

## 9. Plot different features against one another (scatter), against frequency (histogram)

### Histogram

Histogram refers to the frequency of occurrence of variables in an interval. In this case, there are mainly 10 different types of car manufacturing companies, but it is often important to know who has the most number of cars. To do this histogram is one of the trivial solutions which lets us know the total number of car manufactured by a different company.

In [27]:
#df.Make.value_counts().nlargest(40).plot(kind='bar', figsize=(10,5))
#plt.title("Number of cars by make")
#plt.ylabel('Number of cars')
#plt.xlabel('Make');

### Heat Maps

Heat Maps is a type of plot which is necessary when we need to find the dependent variables. One of the best way to find the relationship between the features can be done using heat maps. In the below heat map we know that the price feature depends mainly on the Engine Size, Horsepower, and Cylinders.

In [28]:
#plt.figure(figsize=(10,5))
#c= df.corr()
#sns.heatmap(c,cmap="BrBG",annot=True)
#c

### Scatterplot

We generally use scatter plots to find the correlation between two variables. Here the scatter plots are plotted between Horsepower and Price and we can see the plot below. With the plot given below, we can easily draw a trend line. These features provide a good scattering of points.

In [29]:
#fig, ax = plt.subplots(figsize=(10,6))
#ax.scatter(df['HP'], df['Price'])
#ax.set_xlabel('HP')
#ax.set_ylabel('Price')
#plt.show()

**Hence the above are some of the steps involved in Exploratory data analysis, these are some general steps that you must follow in order to perform EDA. There are many more yet to come but for now, this is more than enough idea as to how to perform a good EDA given any data sets. Stay tuned for more updates.**

## Thank you.